### ISSUE TITLE
Permissions for App?

### ISSUE THREAD

**Issue by larreva** [stevecapacity/Intune-Device-Migration-V6.2#1]
Fantastic work here, love it! 
Do you have a breakdown or explanation of all the required app permissions? I'm not questioning them (well, I haven't found the reason for permission DeviceManagementApps.ReadWrite.All yet), but it would be nice to have an explanation of why each permission is needed, and which functions are dependent on others. 
Do you have this information easily available? Thanks!

**Comment by stevecapacity** [comment]
Thanks.

Currently working on design architecture for the process.

I will include a breakdown of permission use.

I believe Apps.ReadWrite.All may be from a previous version and just didn't clean up yet.
________________________________
From: larreva ***@***.***>
Sent: Tuesday, April 2, 2024 2:32 AM
To: stevecapacity/Intune-Device-Migration-V6.2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stevecapacity/Intune-Device-Migration-V6.2] Permissions for App? (Issue #1)


Fantastic work here, love it!
Do you have a breakdown or explanation of all the required app permissions? I'm not questioning them (well, I haven't found the reason for permission DeviceManagementApps.ReadWrite.All yet), but it would be nice to have an explanation of why each permission is needed, and which functions are dependent on others.
Do you have this information easily available? Thanks!

**Comment by stevecapacity** [comment]
Readme has been updated with permissions description
