### ISSUE TITLE
Group administrators in startmigrate.ps1 for non english

### ISSUE THREAD

**Issue by jydareau** [stevecapacity/Intune-Device-Migration-V6.2#3]
Need to be change

$Groupadmin = Get-WmiObject -Query "Select * From Win32_Group Where LocalAccount = TRUE And SID = 'S-1-5-32-544'"
$GroupName = $Groupadmin.Name
Add-LocalGroupMember -Group $GroupName -Member $migrationAdmin

**Comment by stevecapacity** [comment]
Thank you- will review

**Comment by stevecapacity** [comment]
This has been added to V6.2
